#!/bin/sh

GITREPO=${GIT_REPO:-"git://git.fedorahosted.org/koji"}
GITDIR=/opt/koji
BASEDIR=$(dirname ${GITDIR})

if [ ! -d $GITDIR ]; then
  if [ ! -d $BASEDIR ]; then
    mkdir $BASEDIR
  fi
  
  cd $BASEDIR
  git clone ${GITREPO}
else
  cd ${GITDIR}
  git pull
fi

cd ${GITDIR}
make test-rpm

yum -y localinstall noarch/*.rpm

rpm -qa | grep koji
rpm -ql koji | grep bin

if [ ! -f /usr/bin/brew ]; then
  ln -s /usr/bin/koji /usr/bin/brew
fi

/usr/local/bin/kick-supervisord
