#!/bin/sh

PROCS=$(ps ax | grep supervisord | grep -v kick | grep -v grep)
echo "Found processes:\n${PROCS}"

SPID=$(echo $PROCS | head -1 | awk '{print $1}')
echo $SPID
if [ "x${SPID}" != "x" ]; then
  kill -1 $SPID
fi
